# Generated by Django 5.2.6 on 2025-09-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='products/')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
